<a href="https://colab.research.google.com/github/vedikapathak43-ai/Data_Science_70/blob/main/Practical_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Part a) Create a 3x3 square matrix and compute its determinant.

In [9]:
import numpy as np

print("Enter the elements for the 3x3 matrix, row by row. Separate elements with spaces.")

# Get input for each row
row1_str = input("Enter elements for row 1 (e.g., 1 2 3): ")
row1 = list(map(float, row1_str.split()))

row2_str = input("Enter elements for row 2 (e.g., 4 5 6): ")
row2 = list(map(float, row2_str.split()))

row3_str = input("Enter elements for row 3 (e.g., 7 8 9): ")
row3 = list(map(float, row3_str.split()))

# Create a 3x3 matrix
matrix_a = np.array([
    row1,
    row2,
    row3
])

print("\nOriginal 3x3 Matrix:")
print(matrix_a)

# Compute the determinant
determinant_a = np.linalg.det(matrix_a)

print(f"\nDeterminant of the matrix: {determinant_a}")

Enter the elements for the 3x3 matrix, row by row. Separate elements with spaces.
Enter elements for row 1 (e.g., 1 2 3): 9 8 7
Enter elements for row 2 (e.g., 4 5 6): 6 5 4
Enter elements for row 3 (e.g., 7 8 9): 3 2 1

Original 3x3 Matrix:
[[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]

Determinant of the matrix: 0.0


### Part b) Find the inverse of the matrix.

In [11]:
# Check if the determinant is non-zero to ensure an inverse exists
if np.isclose(determinant_a, 0):
    print("\nThis matrix is singular (determinant is zero) and does not have an inverse.")
else:
    # Compute the inverse of the matrix
    inverse_a = np.linalg.inv(matrix_a)

    print("\nInverse of the matrix:")
    print(inverse_a)

    # Verify by multiplying the matrix by its inverse (should be identity matrix)
    print("\nVerification (Matrix * Inverse):")
    print(np.dot(matrix_a, inverse_a))


This matrix is singular (determinant is zero) and does not have an inverse.


### Part c) Solve the following system of linear equations using NumPy: 2x+3y=10, 4x+5y=20 (take input from user)

In [3]:
import numpy as np

print("Enter coefficients for the first equation (e.g., 2 3 10 for 2x + 3y = 10):")
equ1_str = input()
equ1_coeffs = list(map(float, equ1_str.split()))

print("Enter coefficients for the second equation (e.g., 4 5 20 for 4x + 5y = 20):")
equ2_str = input()
equ2_coeffs = list(map(float, equ2_str.split()))

# Construct the coefficient matrix A
A = np.array([
    equ1_coeffs[:2],
    equ2_coeffs[:2]
])

# Construct the constants vector B
B = np.array([
    equ1_coeffs[2],
    equ2_coeffs[2]
])

print("\nCoefficient Matrix A:")
print(A)
print("\nConstants Vector B:")
print(B)

# Solve the system of linear equations Ax = B
try:
    solution = np.linalg.solve(A, B)
    print("\nSolution (x, y):")
    print(f"x = {solution[0]:.4f}")
    print(f"y = {solution[1]:.4f}")
except np.linalg.LinAlgError as e:
    print(f"\nError: Cannot solve the system. {e}")
    print("This might happen if the matrix is singular (determinant is zero), meaning no unique solution exists.")

Enter coefficients for the first equation (e.g., 2 3 10 for 2x + 3y = 10):
7 16 25
Enter coefficients for the second equation (e.g., 4 5 20 for 4x + 5y = 20):
6 7 12

Coefficient Matrix A:
[[ 7. 16.]
 [ 6.  7.]]

Constants Vector B:
[25. 12.]

Solution (x, y):
x = 0.3617
y = 1.4043
